<a href="https://colab.research.google.com/github/MAvRK7/MAvRK7/blob/main/numpy_school.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


 **Im testing Numpy**

In [2]:
import numpy as np

First doing the array stuff


np.array    thats what its called

In [ ]:
a=np.array([1,2,3]) #1d array
print (a)   #include ()
#2d array
b= np.array([[1,2,3],[4,5,6]])  #put , in between -> [],[]
print (b)
print(a[0], b[0,2]) #the count starts from 0
print (a.shape, b.shape)  #shape gives the rows, col of the matrix
b.ndim  #prints out the dimension of matrix

[1 2 3]
[[1 2 3]
 [4 5 6]]
1 3
(3,) (2, 3)


2

size stuff

In [ ]:
c=np.array ([1,2,3], dtype='int16')
#usually its stored as 34 bit (4 bytes per array) but to save space we can make it 16 or 8 bit
print(c.dtype)
print(c.itemsize )


int16
2


In [ ]:
c.itemsize #this is just in terms of bytes

2

In [ ]:
c.nbytes #number of bytes

6

 *accessing specific array stuff*

In [ ]:
d= np.array([[1,2,3,4,5,6],[11,12,13,14,15,16]])
print(d)

[[ 1  2  3  4  5  6]
 [11 12 13 14 15 16]]


In [ ]:
#get specific element arrayname(r,c)
print(d[0,0])  #use [] brackets

#get specific row
print (d[0,:])

#specific column
print (d[:,1])

1
[1 2 3 4 5 6]
[ 2 12]


Editing Arrays

In [ ]:
#after initializing the array
# to edit a perticular cell

d[0,0]=0
print (d)

# editing a column space
d[:,2] = [7,9]
print (d)

#editing a row space
d[1,:]=[77]
print (d)

#or
#d[0,:]= 10
#print (d)     //remove the "#" to make the top row 10 everywhere

[[ 0  2  7  4  5  6]
 [77 77 77 77 77 77]]
[[ 0  2  7  4  5  6]
 [77 77  9 77 77 77]]
[[ 0  2  7  4  5  6]
 [77 77 77 77 77 77]]


Default ways of filling arrays


filling fully with one number

In [ ]:
#getting the dimensions of another array and filling it full
np.full_like(a,4)  # a is ([1,2,3])

array([4, 4, 4])

In [ ]:
# random
e=np.random.random((2,2))
print(e)

#interger random
f=np.random.randint(7,size=(3,3))  #7 means the highest random number that can come, 7 itself is not included
#f=np.random.randint(4,7,size=(3,3))   HERE 4,5,6 will only be randomized
print (f)


[[0.86366901 0.8912402 ]
 [0.57198285 0.5711509 ]]
[[1 3 0]
 [6 4 4]
 [3 2 6]]


In [ ]:
# identity matrix
np.identity (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeat an array
a1=np.array([[1,2,3]])
a2=np.repeat(a1,3,axis=0)
print(a2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Slicing a array

This slices out an array seperate from the main array

In [ ]:
a3=np.full((5,5),1)
a4=a3[1:4,1:4]
print (a4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#test
a3=np.full((5,5),1)
a4=a3[1:4,1:4]=np.full((3,3),0)
#a4=np.full((3,3),0)
#print (a4)
#a3=np.full((3,3),0)
a3[2,2]=9
print (a3)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


LEARNING
If I slice out from an array and modify it in that line itself, the original also changes

eg- a4=a3[1:4,1:4]=np.full((3,3),0)

but
if i slice out and then im the next line change the slice, the original is unaffected. NOTE - I used full change here not individual

eg- a3=np.full((5,5),1)

  a4=a3[1:4,1:4]

  a4=np.full((3,3),0)

  a3 will be a matrix 5x5 full of 1s and a4 will be a 3x3 full of 0s

  But if you change individual even in diff lines it will change

Copying an array

if for copying one array you absolutely dont want to disturb the other one

In [ ]:
a1=np.array([1,2,3])
b1=a1.copy()
b1[0]=100  #changes in b1 dont affect a1
print (b1)

[100   2   3]


Part of Arrays

In [ ]:
#within a row
# arrayname[row_number, start_index : end_index : stepsize]
d[0, 1:4:2]

array([2, 4])

Math

This part is element wise

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+1
#various commands, a+=2, a-2,a*2, a ** 2 (power)
a*2
np.sin(a) #trig take sin/cos/tan of all arr values
np.sqrt(a) #square root
print(np.dot(a, b))  #matrix multiplication
#or
print(a@b)



32
32


Integer array indexing

In [16]:
#sum of each everything/row/column
a=np.array([[1,2],[3,4]])
print(np.sum(a))
print(np.sum(a,axis=1))  #in a 2D array axis=1 means along rows
print(np.sum(a,axis=0))# in 2D array axis=0 means along cols

10
[3 7]
[4 6]


In [18]:
#matrix ops
print("transpose\n", a.T) #transpose

transpose
 [[1 3]
 [2 4]]


In [5]:
#an array
a= np.array([[1,2],[3,4],[5,6]])
#printing specific number in the matrix
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

#or

print (a[[0,1,2],[0,1,0]])


[1 4 5]
[1 4 5]


In [31]:
#adding a constant to an array, first we tile the constant to match the array's dim and then we add
a3= np.array([[1,2,3],[3,4,5],[5,6,7]])
v = np.array([1, 0, 1])  #we want to add this to each of the array
vv= np.tile(v,(3,1))  #tile it 3 times, once in each row
print (vv)
a4=a3+vv
print ("added result is")
print(a4)

[[1 0 1]
 [1 0 1]
 [1 0 1]]
added result is
[[2 2 4]
 [4 4 6]
 [6 6 8]]


**linear algebra**

this is not element wise